export function formatNumber(num: any): any;
export function padNumber(num: any, length: any): any;
export function removeEmptyArrays(obj: any): {
    [k: string]: any;
};
export function redirect(url: any): void;
export function squeezeWebsiteName(url: any, hasSuffix: any): any;
export function sanitiseString(str: any): any;
export function urlifyString(str: any): any;
export function unurlifyString(str: any): any;
export function objToUrl(obj: any): string;
export function isEmptyObj(obj: any): boolean;
export function isUrl(val: any): boolean;
export function wait(seconds: any): Promise<any>;
export function generateId(length: any): string;
export function getTimestamp(): number;
export function convertToTimestamp(input: any, format: any): number;
export function datetimeToTimestamp(d: any): number;
export function timestampToDatetime(d: any): string;
export function formatTimestamp(timestamp: any, format: any): string;
export function formatDatetime(datetime: any, format: any, timezone: any): string;
export function getTimestampDiff(start: any, end: any, format: any): number;
export function getDatetimeDiff(start: any, end: any, format: any): number;
export function alterTimestamp(operation: any, offset: any, type: any, timestamp: any): any;
export function getDisplayableTimeElapsed(timestamp: any): string;
export function getDisplayableTimeBefore(timestamp: any): string;
export function getRandomNumber(min: any, max: any): any;
export function getRandomDefaultBackground(): string;
export function isToggled(dom_item: any): boolean;
export function toggle(dom_item: any): Promise<any>;
export function blobToDataUrl(val: any, type: any): Promise<any>;
export function isValidUrl(str: any): boolean;
export function scrollHorz(e: any, target: any): void;
export function shuffleArray(arr: any): any;
export function hasErrors(arr: any): boolean;
export function resetErrors(arr: any): any;
export function calcValBeforePercChange(val: any, perc_change: any): number;
export function calcPercChange(a: any, b: any): number;
export function round(num: any, precision: any): string;
export function shortenString(data: any): any;
export function formatUrl(url: any): string;
export function formatAddress(address: any): string;
export function isBetween(x: any, min: any, max: any): boolean;
export function clone(obj: any): any;
export function getTimezones(): {
    name: string;
    zone: string;
}[];
export function getTimezoneZone(id: any): string;
export function timestampToMinute(timestamp: any): number;
export function getIoInstanceStatuses(): {
    code: string;
    colour: string;
}[];
export function calcUserAccessLevel(user: any): {
    access_level: number;
    collections: any[];
};
export function scrollToItemInContainer(data: any): void;
export function getStringLength(str: any): any;
export function getImgSrc(file: any): Promise<any>;
export function imgUrlToBase64(img_url: any): Promise<any>;
export function getBlockchain(blockchain: any): "solana" | "arbitrum" | "bitcoin" | "ethereum" | "polygon" | "sui";
export function getWeightedRandom(d: any): any;
export function removeAccents(str: any): any;
export function getSubstringOccurrenceCount(d: any): number;
export function compressImage(d: any): any;
export function copyToClipboard(text: any): void;
